# ------------------------------------------------------------------------------
# DBT PROJECT CONFIGURATION
# ------------------------------------------------------------------------------

# Project name (lowercase + underscores only)
name: "core_telecoms_dbt"
version: "1.0.0"

# This tells dbt which profile in profiles.yml to use
profile: "core_telecoms_dbt"

# ------------------------------------------------------------------------------
# PATHS (Where dbt will look for your project files)
# ------------------------------------------------------------------------------
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# ------------------------------------------------------------------------------
# CLEAN TARGETS
# These directories are deleted when running `dbt clean`
# ------------------------------------------------------------------------------
clean-targets:
  - "target"
  - "dbt_packages"

# ------------------------------------------------------------------------------
# MODELS CONFIGURATION
# This section controls how models behave inside the project.
# ------------------------------------------------------------------------------
models:
  core_telecoms_dbt:

    # --------------------------------------------------------------------------
    # 1. DEFAULT CONFIG FOR ALL MODELS IN THE PROJECT
    # This sets a default materialization for everything unless overridden.
    # --------------------------------------------------------------------------
    +materialized: view

    # --------------------------------------------------------------------------
    # 2. CONFIG FOR MODELS IN: models/example/
    # --------------------------------------------------------------------------
    example:
      +materialized: view   # You can change this later if needed

    # --------------------------------------------------------------------------
    # 3. CONFIG FOR MODELS IN: models/staging/
    # Staging models usually clean and rename raw source columns.
    # --------------------------------------------------------------------------
    staging:
      +enabled: true         # Explicitly enable all models in models/staging/
      +materialized: view    # Staging models should remain views (best practice)
